project_id = "vxqfqexeviwjycyrojww"

[functions.chat]
verify_jwt = false

[functions.hash-password]
verify_jwt = false

[functions.chat-api]
verify_jwt = false

[functions.user-api]
verify_jwt = false

[functions.auth-admin]
verify_jwt = false

[functions.password-recovery]
verify_jwt = false